server:
  port: 8003
spring:
  application:
    name: consumer1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

service:
  app:
    name: providerType1